use_frameworks!
platform :ios, "10.3"

target 'Lookup_Example' do
  pod 'Lookup', :path => '../'

  target 'Lookup_ExampleTests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
